services:
  - type: web
    name: eaglercraft-websocket
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MAX_CONNECTIONS
        value: 100
      - key: PING_INTERVAL
        value: 30000
      - key: PING_TIMEOUT
        value: 10000